version: '3.4'

services:
  dsc-docker:
    image: frankfletcher/dsc-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    hostname: dsc-docker
    volumes:
      - "~/SPRINGBOARD_FILES:/home/student/SPRINGBOARD_FILES"

